/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <iostream>
#include <stdio.h>
/* Header for class com_example_kevin_opencvdemo_OpenCVClass */

using namespace std;
using namespace cv;

#ifndef _Included_com_example_kevin_opencvdemo_OpenCVClass
#define _Included_com_example_kevin_opencvdemo_OpenCVClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kevin_opencvdemo_OpenCVClass
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);

JNIEXPORT void JNICALL Java_com_example_kevin_opencvdemo_OpenCVClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
